# Generated by Django 4.2.25 on 2025-10-26 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente de Pagamento'), ('Pago', 'Pago - Processando'), ('Enviado', 'Enviado'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total do Pedido')),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Frete')),
                ('tipo_pagamento', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], default='pix', max_length=20, verbose_name='Método de Pagamento')),
                ('transacao_id', models.CharField(blank=True, help_text='ID do gateway de pagamento', max_length=255, null=True, verbose_name='ID Transação')),
                ('url_pagamento', models.URLField(blank=True, help_text='URL do Boleto ou QR Code Pix', max_length=500, null=True, verbose_name='URL de Pagamento')),
                ('endereco_entrega_json', models.JSONField(help_text='Cópia do endereço no momento do pedido', verbose_name='Endereço de Entrega (JSON)')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp de Contato')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Rastreio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido_compra',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_joia', models.CharField(max_length=255, verbose_name='Nome da Joia')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário na Compra')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('joia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='catalog.joia', verbose_name='Joia Original')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'pedido_item',
                'unique_together': {('pedido', 'nome_joia')},
            },
        ),
    ]
