# Generated by Django 4.2.25 on 2025-10-26 19:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando_pagamento', 'Aguardando Pagamento'), ('pago', 'Pago'), ('em_preparacao', 'Em Preparação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_pagamento', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto'), ('pix', 'PIX')], max_length=10)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_entrega', models.CharField(max_length=255)),
                ('cep_entrega', models.CharField(max_length=9)),
                ('rua_entrega', models.CharField(max_length=255)),
                ('numero_entrega', models.CharField(max_length=10)),
                ('complemento_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro_entrega', models.CharField(max_length=100)),
                ('cidade_entrega', models.CharField(max_length=100)),
                ('estado_entrega', models.CharField(max_length=2)),
                ('telefone_contato', models.CharField(max_length=15)),
                ('email_contato', models.EmailField(max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'vendas_pedido',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='catalog.joia')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'vendas_item_pedido',
            },
        ),
    ]
