# Generated by Django 4.2.25 on 2025-10-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagem da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('em_destaque', models.BooleanField(default=False, verbose_name='Em Destaque na Home')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'catalogo_categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Subcategoria')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'db_table': 'catalogo_subcategoria',
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Joia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Joia')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('desconto', models.PositiveIntegerField(default=0, help_text='Desconto em porcentagem')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque Atual')),
                ('disponivel', models.BooleanField(default=True)),
                ('em_destaque', models.BooleanField(default=False)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='joias/', verbose_name='Imagem Principal')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joias', to='catalog.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joias_subcategoria', to='catalog.subcategoria')),
            ],
            options={
                'verbose_name': 'Joia',
                'verbose_name_plural': 'Joias',
                'db_table': 'catalogo_joia',
                'ordering': ['nome'],
            },
        ),
    ]
